// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/data.protobuf

package com.ajjpj.asysmon.data;

public final class DataProtobuf {
  private DataProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GlobalDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 timestamp = 1;
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    long getTimestamp();

    // repeated .GlobalDataItem items = 2;
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    java.util.List<com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem> 
        getItemsList();
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem getItems(int index);
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    java.util.List<? extends com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GlobalData}
   */
  public static final class GlobalData extends
      com.google.protobuf.GeneratedMessage
      implements GlobalDataOrBuilder {
    // Use GlobalData.newBuilder() to construct.
    private GlobalData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GlobalData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GlobalData defaultInstance;
    public static GlobalData getDefaultInstance() {
      return defaultInstance;
    }

    public GlobalData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                items_ = new java.util.ArrayList<com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              items_.add(input.readMessage(com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ajjpj.asysmon.data.DataProtobuf.GlobalData.class, com.ajjpj.asysmon.data.DataProtobuf.GlobalData.Builder.class);
    }

    public static com.google.protobuf.Parser<GlobalData> PARSER =
        new com.google.protobuf.AbstractParser<GlobalData>() {
      public GlobalData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // repeated .GlobalDataItem items = 2;
    public static final int ITEMS_FIELD_NUMBER = 2;
    private java.util.List<com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem> items_;
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    public java.util.List<com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    public java.util.List<? extends com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .GlobalDataItem items = 2;</code>
     */
    public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      timestamp_ = 0L;
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(2, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ajjpj.asysmon.data.DataProtobuf.GlobalData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GlobalData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ajjpj.asysmon.data.DataProtobuf.GlobalDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ajjpj.asysmon.data.DataProtobuf.GlobalData.class, com.ajjpj.asysmon.data.DataProtobuf.GlobalData.Builder.class);
      }

      // Construct using com.ajjpj.asysmon.data.DataProtobuf.GlobalData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalData_descriptor;
      }

      public com.ajjpj.asysmon.data.DataProtobuf.GlobalData getDefaultInstanceForType() {
        return com.ajjpj.asysmon.data.DataProtobuf.GlobalData.getDefaultInstance();
      }

      public com.ajjpj.asysmon.data.DataProtobuf.GlobalData build() {
        com.ajjpj.asysmon.data.DataProtobuf.GlobalData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ajjpj.asysmon.data.DataProtobuf.GlobalData buildPartial() {
        com.ajjpj.asysmon.data.DataProtobuf.GlobalData result = new com.ajjpj.asysmon.data.DataProtobuf.GlobalData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ajjpj.asysmon.data.DataProtobuf.GlobalData) {
          return mergeFrom((com.ajjpj.asysmon.data.DataProtobuf.GlobalData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ajjpj.asysmon.data.DataProtobuf.GlobalData other) {
        if (other == com.ajjpj.asysmon.data.DataProtobuf.GlobalData.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ajjpj.asysmon.data.DataProtobuf.GlobalData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ajjpj.asysmon.data.DataProtobuf.GlobalData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 timestamp = 1;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // repeated .GlobalDataItem items = 2;
      private java.util.List<com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = new java.util.ArrayList<com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem>(items_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public java.util.List<com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public Builder setItems(
          int index, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public Builder setItems(
          int index, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public Builder addItems(com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public Builder addItems(
          int index, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public Builder addItems(
          com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public Builder addItems(
          int index, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          super.addAll(values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public java.util.List<? extends com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.getDefaultInstance());
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.getDefaultInstance());
      }
      /**
       * <code>repeated .GlobalDataItem items = 2;</code>
       */
      public java.util.List<com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GlobalData)
    }

    static {
      defaultInstance = new GlobalData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GlobalData)
  }

  public interface GlobalDataItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string identifier = 1;
    /**
     * <code>required string identifier = 1;</code>
     */
    boolean hasIdentifier();
    /**
     * <code>required string identifier = 1;</code>
     */
    java.lang.String getIdentifier();
    /**
     * <code>required string identifier = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdentifierBytes();

    // required int32 value = 2;
    /**
     * <code>required int32 value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required int32 value = 2;</code>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code GlobalDataItem}
   */
  public static final class GlobalDataItem extends
      com.google.protobuf.GeneratedMessage
      implements GlobalDataItemOrBuilder {
    // Use GlobalDataItem.newBuilder() to construct.
    private GlobalDataItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GlobalDataItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GlobalDataItem defaultInstance;
    public static GlobalDataItem getDefaultInstance() {
      return defaultInstance;
    }

    public GlobalDataItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalDataItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              identifier_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalDataItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalDataItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.class, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder.class);
    }

    public static com.google.protobuf.Parser<GlobalDataItem> PARSER =
        new com.google.protobuf.AbstractParser<GlobalDataItem>() {
      public GlobalDataItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalDataItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalDataItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string identifier = 1;
    public static final int IDENTIFIER_FIELD_NUMBER = 1;
    private java.lang.Object identifier_;
    /**
     * <code>required string identifier = 1;</code>
     */
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          identifier_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <code>required int32 value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 value = 2;</code>
     */
    public int getValue() {
      return value_;
    }

    private void initFields() {
      identifier_ = "";
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIdentifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdentifierBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdentifierBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GlobalDataItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalDataItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalDataItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.class, com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.Builder.class);
      }

      // Construct using com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        identifier_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ajjpj.asysmon.data.DataProtobuf.internal_static_GlobalDataItem_descriptor;
      }

      public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem getDefaultInstanceForType() {
        return com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.getDefaultInstance();
      }

      public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem build() {
        com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem buildPartial() {
        com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem result = new com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.identifier_ = identifier_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem) {
          return mergeFrom((com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem other) {
        if (other == com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem.getDefaultInstance()) return this;
        if (other.hasIdentifier()) {
          bitField0_ |= 0x00000001;
          identifier_ = other.identifier_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdentifier()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ajjpj.asysmon.data.DataProtobuf.GlobalDataItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string identifier = 1;
      private java.lang.Object identifier_ = "";
      /**
       * <code>required string identifier = 1;</code>
       */
      public boolean hasIdentifier() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string identifier = 1;</code>
       */
      public java.lang.String getIdentifier() {
        java.lang.Object ref = identifier_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          identifier_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string identifier = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdentifierBytes() {
        java.lang.Object ref = identifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string identifier = 1;</code>
       */
      public Builder setIdentifier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string identifier = 1;</code>
       */
      public Builder clearIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000001);
        identifier_ = getDefaultInstance().getIdentifier();
        onChanged();
        return this;
      }
      /**
       * <code>required string identifier = 1;</code>
       */
      public Builder setIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        identifier_ = value;
        onChanged();
        return this;
      }

      // required int32 value = 2;
      private int value_ ;
      /**
       * <code>required int32 value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 value = 2;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>required int32 value = 2;</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GlobalDataItem)
    }

    static {
      defaultInstance = new GlobalDataItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GlobalDataItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GlobalData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalDataItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GlobalDataItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/data.protobuf\"?\n\nGlo" +
      "balData\022\021\n\ttimestamp\030\001 \002(\003\022\036\n\005items\030\002 \003(" +
      "\0132\017.GlobalDataItem\"3\n\016GlobalDataItem\022\022\n\n" +
      "identifier\030\001 \002(\t\022\r\n\005value\030\002 \002(\005B\030\n\026com.a" +
      "jjpj.asysmon.data"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GlobalData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GlobalData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GlobalData_descriptor,
              new java.lang.String[] { "Timestamp", "Items", });
          internal_static_GlobalDataItem_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_GlobalDataItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GlobalDataItem_descriptor,
              new java.lang.String[] { "Identifier", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
